# Variables

In [1]:
a = 3
b = a
print(id(a), id(b))

# 같은 주소 값이 나옴

a += 2
print(a,b,id(a),id(b))

# 다른 주소 값이 나오며 값도 달라짐

140706090230224 140706090230224
5 3 140706090230288 140706090230224


In [2]:
# 모두 같은 주소를 잡음

a = [1,2,3]
b = a

print(id(a), id(b))

a += [4,5,6]
a,b,id(a),id(b)

2896086022984 2896086022984


([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], 2896086022984, 2896086022984)

In [3]:
# Immutable

def test1(a):
    a = 2

a=1
test1(a)
a

1

In [4]:
# mutable

def test2(a):
    a.append("World")

a = ["Hello"]
test2(a)
a

['Hello', 'World']

## Basic Variables

In [5]:
a = 100
b = 0b100
a, b

(100, 4)

In [6]:
# binary로 표현되며 이는 string이 된다.
bin(a)

'0b1100100'

In [7]:
print(type(a))
print(type(bin(a)))

<class 'int'>
<class 'str'>


In [8]:
# hexa로 나타나게 된다
hex(a)

'0x64'

In [9]:
x = [1,2,3]
x.append(10)

In [10]:
x

[1, 2, 3, 10]

In [11]:
y = [1,2,3,10]
y

[1, 2, 3, 10]

In [12]:
print("Object가 같은가?",x is y)
print("Object의 value가 같은가?",x == y)

Object가 같은가? False
Object의 value가 같은가? True


In [13]:
3 > 4, 13/2, 13//2, 13%2

(False, 6.5, 6, 1)

In [14]:
# Boolean은 True == 1, False == 0

True + True

2

In [15]:
True * True

1

In [16]:
# logarithm expression

x, y = 1e6, 1e-3
x,y

(1000000.0, 0.001)

In [17]:
# complex number
c = 1.5 +0.7j
c.real, c.imag

(1.5, 0.7)

In [18]:
# input, output
x = input()
print(x)
print(type(x))

5
5
<class 'str'>


In [19]:
# input and type casting
x = int(input())
print(x)
print(type(x))

5
5
<class 'int'>


In [20]:
a = [1,2,3,4]
b = 3
b in a, 5 not in a

(True, True)

## Container type
- string, list, tuple, string

### String

In [21]:
s.capitalize(), s.upper(), s.lower(), s.swapcase()

NameError: name 's' is not defined

In [ ]:
s.isalnum(), s.isalpha(), s.isdigit()

In [ ]:
s2 = "123"
s2.upper(), s.isalpha(), s2.isdigit()

In [ ]:
s1 = "animals: cat, dog, cat, cat, cat, wow!!"
s2 = "cat"
s1.find(s2), s1.index(s2), s1.rfind(s2) # 맨 뒤

In [ ]:
"   Too many space.    ".strip()

In [ ]:
"HELLO".replace("E","e")

In [24]:
x = "I am home."
x.split(' ')

['I', 'am', 'home.']

In [ ]:
":".join(['1','2','3'])

## Common sequence function
- array, string, list, tuple **(Not applied in dictionary)**
- Indexing and Slicing

In [ ]:
# inedexing
a = "hello world!"
print(a[0], a[1], a[-1], a[-2])

# slicing
print(a[0:5], a[0:5:2]) # start, end(excluding), step(or stride)
print(a[:-1])
print(a[:])
print(a[::2])

In [ ]:
# string은 immuatable 하기 때문에 assign 불가하다.
a[0] = 'H'

In [ ]:
for x in "Banana":
    if x.islower():
        print(x.upper())
    else:
        print(x)

## Iterable objects
- array, string, list, tuples, dict

In [ ]:
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

myit, next(myit), next(myit), next(myit)

In [ ]:
a = list(range(5))

# 뒤에서부터 읽기 가능
a[-1::-1]

In [ ]:
b = [[0,1,2,3],[3,4,5],[6,7,8]]
print(b[0], b[1], b[2])
print(b[0][1:2])

In [ ]:
c = (0,1,2,3,4)
c[0], c[:3], c[-1]

In [ ]:
a[0] = 100
a # list is mutable

In [ ]:
a.append(77); a # in-place execution: object a change, so this function didn't show anything in command

In [ ]:
sum(a), max(a), min(a), len(a), any(a), all(a)

# any: 어떤 것 하나라도 True가 있느냐
# all: 모두 True이냐 (0 이상이면 모두 True)

In [ ]:
# enumerate
a = [1,2,3,4]
for idx, x in enumerate(a):
    print(idx,":", x)

In [ ]:
# 스스로 설정할 수 있음
for idx, x in enumerate(a, 20):
    print(idx, ":",x)

In [ ]:
# zip 으로 묶기
a = [1,2,3,4]
b = ['a','b','c','d']
for i in zip(a,b):
    print(i)

In [27]:
a = [1,2,3,4]
print(a.pop())
print(a.pop())
print(a.pop())
print(a)

4
3
2
[1]


In [35]:
[1,2,3] + ['a','b','c'] + [[1,2],[3,4]]

[1, 2, 3, 'a', 'b', 'c', [1, 2], [3, 4]]

In [33]:
# tuple
my_tuple = (1,2,3,'Hello',[1,2])
print(my_tuple)
my_tuple[4][0] = 2
print(my_tuple)

# tuple 자체는 수정할 수 없으나, 그 내부 값은 수정할 수 있음

(1, 2, 3, 'Hello', [1, 2])
(1, 2, 3, 'Hello', [2, 2])


In [36]:
(1,2) + (3,4)

(1, 2, 3, 4)

In [39]:
# set
a=set([1,2,3,1,2,3,4])
a

{1, 2, 3, 4}

In [53]:
# dictionary
d = {"grade":3, "age":15, "name": "Kim"}
type(d)
d['age'], d['grade']

(15, 3)

In [45]:
print(d)

{'grade': 3, 'age': 15, 'name': 'Kim'}


In [46]:
d.items()

dict_items([('grade', 3), ('age', 15), ('name', 'Kim')])

In [48]:
d.keys() # 키만 보는 것

dict_keys(['grade', 'age', 'name'])

In [49]:
d.values()

dict_values([3, 15, 'Kim'])

In [54]:
print(d.pop('name'))
print(d)

Kim
{'grade': 3, 'age': 15}


In [55]:
d['height'] = 175

In [56]:
d

{'grade': 3, 'age': 15, 'height': 175}

In [47]:
dir(dict)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

## Sorting

### List sorting

In [ ]:
a = [1,4,3,6,9,10,7]
sorted(a)

In [ ]:
sorted(a, reverse=True)

In [ ]:
# 순서 바꿈

for i in reversed(a):
    print(i)

In [ ]:
a.sort(); a # in-place function

In [ ]:
a.sort(reverse=True); 

### Array sorting

In [85]:
# array sorting
import numpy as np
a = np.array([1,2,4,5,6,11,5,4,7,3])
a

array([ 1,  2,  4,  5,  6, 11,  5,  4,  7,  3])

In [86]:
a.sort()

In [87]:
a

array([ 1,  2,  3,  4,  4,  5,  5,  6,  7, 11])

In [89]:
# array 에도 sort 가 있으나, reverse=True 는 없다
a[::-1]

array([11,  7,  6,  5,  5,  4,  4,  3,  2,  1])

### Dataframe sorting

In [90]:
import pandas as pd
 
df = pd.DataFrame({'order':[2,1,3],
                   'name': ['park', 'kim', 'lee'],
                   'age': [30,20,40]}, index = ['a','b','c'])
df

order  name  age
a      2  park   30
b      1   kim   20
c      3   lee   40

In [91]:
df.sort_values(by='order')

order  name  age
b      1   kim   20
a      2  park   30
c      3   lee   40

In [92]:
df.sort_values(by='order', ascending=False)

order  name  age
c      3   lee   40
a      2  park   30
b      1   kim   20

In [93]:
df.sort_index(ascending=False)

order  name  age
c      3   lee   40
b      1   kim   20
a      2  park   30

## Comprehension examples

In [63]:
A = list(range(6)); B = ['a','b','c']; C = [(3,4),(7,24)]

In [58]:
[3 * x for x in A]

[0, 3, 6, 9, 12, 15]

In [59]:
[3 * x for x in A if x < 3]

[0, 3, 6]

In [61]:
[(x, x**2) for x in A if x % 2 == 0]

[(0, 0), (2, 4), (4, 16)]

In [65]:
[(x,y) for x in A for y in B if x == 3]

[(3, 'a'), (3, 'b'), (3, 'c')]

In [66]:
import numpy as np

[np.sqrt((x**2)+(y**2)) for x,y in C]

[5.0, 25.0]

## if / for / while / break / continue

In [68]:
list(range(2,10,2))

[2, 4, 6, 8]

In [71]:
x = list(range(2,10,2))
for i in x:
    print(i * 10)

20
40
60
80


In [72]:
[i * 10 for i in x]

[20, 40, 60, 80]

In [75]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is', word, end=" and ")

Python is cool and Python is powerful and Python is readable and 

In [77]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is {} {}'.format(word, 'really'))

Python is cool really
Python is powerful really
Python is readable really


In [82]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is %s' %word)

Python is cool
Python is powerful
Python is readable


In [83]:
z = -3
while abs(z) < 20:
    z = z**2 + 1
    print(z)

10
101


In [84]:
a = [1,2,0,4]
for i in a:
    if i == 0:
        continue
    elif i%2 == 0:
        print(i,"is even")
    else:
        print(i,"is odd")

1 is odd
2 is even
4 is even


## Functions and Classes

In [95]:
def my_func1(x):
    return x**2

my_func1(10)

100

In [97]:
def my_func2(x,y = 5):
    import numpy as np
    return np.sqrt(x**2+y**2)

my_func2(3,4)

5.0

In [99]:
# default 지정

my_func2(3)

5.830951894845301

In [101]:
# scope with global
x,y = 11, 12
print('outside of function:', x, id(x), y, id(y))

def my_func3():
    x = 77
    
    global y
    y = 88
    print('inside of function:', x, id(x), y, id(y))
    
my_func3()
print('outside of function:', x, id(x), y, id(y))

outside of function: 11 140706090230480 12 140706090230512
inside of function: 77 140706090232592 88 140706090232944
outside of function: 11 140706090230480 88 140706090232944


In [103]:
import sys

class myClass:
    """This is an example class for Python."""
    def __init__(self):
        self.data = [77,88]
    
    i,j = 234, 235
    
    def func1(self):
        return ("hello, world!")

In [106]:
x = myClass()

x.data, x.i, x.j, x.func1(), x.__doc__

([77, 88], 234, 235, 'hello, world!', 'This is an example class for Python.')

In [107]:
dir(x)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'data',
 'func1',
 'i',
 'j']

In [110]:
help(x)

Help on myClass in module __main__ object:

class myClass(builtins.object)
 |  This is an example class for Python.
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  func1(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  i = 234
 |  
 |  j = 235

