In [1]:
import numpy as np

### Eigen value, Eigen vector
- A * v = lambda * v

In [2]:
A = np.array([[0.,1.],
             [-2.,-3.]])
A

array([[ 0.,  1.],
       [-2., -3.]])

In [3]:
A.shape

(2, 2)

In [5]:
# Linear algebra eigen

eigvals, eigvecs = np.linalg.eig(A)
print("Eigen values: ", eigvals)
print("Eigen vector: ",eigvecs)

Eigen values:  [-1. -2.]
Eigen vector:  [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [6]:
# 따라서 eigen values 와 vector를 곱하면 답이 같음

eigvals[0]*eigvecs[:,0]

array([-0.70710678,  0.70710678])

In [7]:
A.dot(eigvecs[:,0])

array([-0.70710678,  0.70710678])

## LU decomposition

In [8]:
from scipy.linalg import lu

In [13]:
A = np.arange(1,10).reshape((3,3))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
P,L,U = lu(A)

In [17]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [19]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [20]:
U

array([[ 7.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [ 0.00000000e+00,  8.57142857e-01,  1.71428571e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.58603289e-16]])

In [21]:
print(P.dot(L).dot(U))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [22]:
# 단순 LU decompostion 보다 PLU 가 더 빠름

print(L.dot(U))

[[7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]]


## QR decomposition

In [23]:
from scipy.linalg import qr

In [24]:
A = np.arange(1,7).reshape((3,2))
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
Q, R = qr(A, mode='full')

In [26]:
# Orthnomal matrix

print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [27]:
# Upper rectanglular matrix

print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [28]:
# Orthgonality check: 거의 0에 가까움
(Q[:,0]*Q[:,1]).sum()

-1.6653345369377348e-16

In [29]:
(Q[:,1]*Q[:,2]).sum()

0.0

In [30]:
(Q[:,2]*Q[:,0]).sum()

-1.1102230246251565e-16

In [33]:
# normality check

for i in range(3):
    vec = np.array(Q[:,i])
    print((vec**2).sum())

1.0
1.0
0.9999999999999998


## Eigen decomposition


In [34]:
A = np.array([[6,2],[2,3]])
A

array([[6, 2],
       [2, 3]])

In [35]:
eigvals, eigvecs = np.linalg.eig(A)

In [36]:
eigvals

array([7., 2.])

In [37]:
eigvecs

array([[ 0.89442719, -0.4472136 ],
       [ 0.4472136 ,  0.89442719]])

In [40]:
P = eigvecs
D = np.diag(eigvals) # diagonal matrix를 만들어줌

In [39]:
print(D)

[[7. 0.]
 [0. 2.]]


In [41]:
P.dot(D).dot(P.T)

array([[6., 2.],
       [2., 3.]])

## SVD Decompostion

In [45]:
A = np.arange(1,7).reshape((3,2))
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
U, S, VT = np.linalg.svd(A, full_matrices=True)

In [47]:
# 이를 S 의 3 by 2 형태로 만들어야 함
S

array([9.52551809, 0.51430058])

In [58]:
Smat = np.diag(S)
print(Smat)
Smat = np.vstack((Smat,[0,0]))

# np.vstack: 뒤에 더 쌓는 것

[[9.52551809 0.        ]
 [0.         0.51430058]]


In [54]:
print(Smat)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [51]:
U.dot(Smat).dot(VT)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])